name: release
on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build sphinx documentation
      run: |
        make html
    - name: Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.SFTP_HOST }}
        FTP_USERNAME: ${{ secrets.SFTP_USER }}
        FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        LOCAL_DIR: build/html
        METHOD: sftp
        PORT: 22
        ARGS: --delete
